version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout  # check out src code into working directory

      - run:
          name: Set up
          command: |
            git submodule sync; git submodule update --init
            sudo apt-get update; sudo apt-get install libsfml-dev

      - run:
          name: Compile
          command: make test

      - run:
          name: Test
          command: ./bin/gtest