version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:stretch   # Debian stretch, has git pre-installed

    steps:
      - checkout  # check out src code into working directory

      - run:
          name: Set up
          command: |
            sudo apt-get update
            git submodule sync; git submodule update --init # initialize git submodules
            sudo apt-get install libsfml-dev                # version 2.4.2
            sudo apt-get install libjsoncpp-dev             # version 1.7.3
            cd /usr/include;sudo ln -s jsoncpp/json json    # change include path so it matches local build

      - run:
          name: Compile
          command: make test

      - run:
          name: Test
          command: ./bin/gtest