version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date


# The following was for Circle CI 1.0
# Based on https://github.com/tjun/googletest-circleci
#dependencies:
#  pre:
#    - cd googletest/googletest; mkdir build; cd build; cmake ..; make
#    - sudo apt-get update; sudo apt-get install gcc-5; sudo apt-get install g++-5
#    - sudo apt-get install libsfml-dev

#compile:
#  pre:
#    override:
#      - make
#     - make test

#test:
#  override:
#    - ./bin/gtest

#checkout:
#  post:
#    - git submodule init
#    - git submodule update